/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Cezarino Hora
 */
public class Frmradiobutton extends javax.swing.JFrame {

    /**
     * Creates new form Frmradiobutton
     */
    public Frmradiobutton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        lblexemploradiobutton = new javax.swing.JLabel();
        lblresposta = new javax.swing.JLabel();
        txtresposta = new javax.swing.JTextField();
        lbllingprogr = new javax.swing.JPanel();
        rbjavascript = new javax.swing.JRadioButton();
        rbjava = new javax.swing.JRadioButton();
        rbphp = new javax.swing.JRadioButton();
        btnescolher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblexemploradiobutton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblexemploradiobutton.setText("Exemplo Radio Button");
        getContentPane().add(lblexemploradiobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        lblresposta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblresposta.setText("Resposta:");
        getContentPane().add(lblresposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        txtresposta.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtresposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrespostaActionPerformed(evt);
            }
        });
        getContentPane().add(txtresposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 248, 39));

        lbllingprogr.setBorder(javax.swing.BorderFactory.createTitledBorder("Linguagens de Programação"));

        grupo.add(rbjavascript);
        rbjavascript.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        rbjavascript.setText("JavaScript");

        grupo.add(rbjava);
        rbjava.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        rbjava.setText("Java");

        grupo.add(rbphp);
        rbphp.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        rbphp.setText("PHP");

        javax.swing.GroupLayout lbllingprogrLayout = new javax.swing.GroupLayout(lbllingprogr);
        lbllingprogr.setLayout(lbllingprogrLayout);
        lbllingprogrLayout.setHorizontalGroup(
            lbllingprogrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbllingprogrLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(rbjavascript)
                .addGap(45, 45, 45)
                .addComponent(rbphp)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(lbllingprogrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lbllingprogrLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(rbjava)
                    .addContainerGap(336, Short.MAX_VALUE)))
        );
        lbllingprogrLayout.setVerticalGroup(
            lbllingprogrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbllingprogrLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(lbllingprogrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbjavascript)
                    .addComponent(rbphp))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(lbllingprogrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lbllingprogrLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(rbjava)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );

        getContentPane().add(lbllingprogr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 460, 130));

        btnescolher.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnescolher.setText("Escolher");
        btnescolher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnescolherActionPerformed(evt);
            }
        });
        getContentPane().add(btnescolher, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 140, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtrespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrespostaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrespostaActionPerformed

    private void btnescolherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnescolherActionPerformed
        // Botão Escolher
        if(rbjava.isSelected()){
            // A opção escolhida foi Java
            txtresposta.setText("Java");
            
        }else if (rbjavascript.isSelected()){
            // A opção escolhida foi JavaScript
            txtresposta.setText(rbjavascript.getText());
            
        }else if (rbphp.isSelected()){
            // A opção escolhida foi PHP
            txtresposta.setText("PHP");
        }
    }//GEN-LAST:event_btnescolherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmradiobutton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmradiobutton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmradiobutton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmradiobutton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmradiobutton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnescolher;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel lblexemploradiobutton;
    private javax.swing.JPanel lbllingprogr;
    private javax.swing.JLabel lblresposta;
    private javax.swing.JRadioButton rbjava;
    private javax.swing.JRadioButton rbjavascript;
    private javax.swing.JRadioButton rbphp;
    private javax.swing.JTextField txtresposta;
    // End of variables declaration//GEN-END:variables
}
